name: CI/CD

on:
  push

env:
  PACKAGE_NAME: "investigator"
  MANIFEST_NAME: "system.json"
  MANIFEST_PATH: "public/system.json"
  ZIP_FILE_NAME: "investigator.zip"

jobs:
  parse_tag:
    runs-on: ubuntu-latest
    environment: release
    outputs:
      tag_version: ${{ steps.get_tag_version.outputs.group1 }}
      tag_prerelease: ${{ steps.get_tag_version.outputs.group2 }}
    steps:
      - name: Get tag versions
        if: github.ref_type == 'tag'
        id: get_tag_version
        uses: actions-ecosystem/action-regex-match@v2.0.2
        with:
          regex: '^refs/tags\/(v\d+\.\d+\.\d+(?:$|(-[a-z0-9._-]+)))'
          text: ${{ github.ref }}

  instrument_parse_tag:
    runs-on: ubuntu-latest
    environment: release
    # if: github.ref_type == 'tag'
    needs: parse_tag
    steps:
      - name: Instrument tags capture
        run: |
          echo "tag_version: ${{ needs.parse_tag.outputs.tag_version }}"
          echo "tag_prerelease: ${{ needs.parse_tag.outputs.tag_prerelease }}"

  # update_manifest:
  #   runs-on: ubuntu-latest
  #   environment: release
  #   needs: parse_tag
  #   steps:
  #     - name: Update manifest
  #       if: github.ref_type == 'tag' && needs.parse_tag.outputs.tag_version != ''
  #       env:
  #         CI_COMMIT_TAG: ${{ needs.parse_tag.outputs.tag_version }}
  #         CI_PROJECT_PATH: ${{ github.repository }}
  #       run: |
  #         echo "CI_COMMIT_TAG: $CI_COMMIT_TAG"
  #         echo "CI_PROJECT_PATH: $CI_PROJECT_PATH"
  #         ./tasks.js updateManifestFromCIPush
  #         cat $MANIFEST_PATH

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: parse_tag
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Activate pnpm
        run: corepack enable

      - name: Instrumentation
        run: |
          pwd
          ls -l
          cat tsconfig.json
          export
          node --version
          pnpm --version

      - name: Install dependencies
        run: pnpm i

      - name: Instrument tsc version
        run: npx tsc --version

      - name: Update manifest
        if: github.ref_type == 'tag' && needs.parse_tag.outputs.tag_version != ''
        env:
          CI_COMMIT_TAG: ${{ needs.parse_tag.outputs.tag_version }}
          CI_PROJECT_PATH: ${{ github.repository }}
        run: |
          echo "CI_COMMIT_TAG: $CI_COMMIT_TAG"
          echo "CI_PROJECT_PATH: $CI_PROJECT_PATH"
          ./tasks.js updateManifestFromCIPush
          cat $MANIFEST_PATH

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm package

      - name: Upload package file
        uses: actions/upload-artifact@v3
        with:
          name: package-zip
          path: package/investigator.zip

      - name: Upload manifest
        uses: actions/upload-artifact@v3
        with:
          name: manifest
          path: public/system.json


  publish:
    needs:
      - build
      - parse_tag
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
    if: needs.parse_tag.outputs.tag_version != ''
    env:
      version: ${{ needs.parse_tag.outputs.tag_version }}
      prerelease: ${{ needs.parse_tag.outputs.tag_prerelease }}
    steps:
      - name: Download package
        uses: actions/download-artifact@v3
        with:
          name: package-zip

      - name: Download manifest
        uses: actions/download-artifact@v3
        with:
          name: manifest

      - name: Look around
        run: |
          pwd
          ls -l

      - name: Update Release With Files
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ env.version }}
          draft: true
          prerelease: ${{ env.prerelease != '' }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './system.json, ./investigator.zip'
          tag: ${{ env.version }}
          body: >
            **Installation:** To manually install this release, please use the
            following manifest URL: ***TBD***
